### ISSUE TITLE
Merging onto dev

### ISSUE THREAD

**Issue by mghosh00** [SABS-R3-Epidemiology/abm-project-2023#11]
It would be good to merge what we have now from the feature-minicell-class and test-minicell-class branches onto dev so that we can see the continuous integration working and to have a working copy of the project saved to dev. This way, all future branches we make can branch off dev, and we don't end up in a situation where we are trying to fix CI errors at the last minute

**Comment by mghosh00** [comment]
The first thing to do would be to accept the Feature workflows pull request, as then we at least have all of this online

**Comment by abbie-evans** [comment]
The feature workflows pull request is now passing all checks and so is ready to be merged
