### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by tomcodewizard** [SABS-R3-Epidemiology/abm-project-2023#22]
Will get started on the wiki.

Please could people put essential information relating to their work for the wiki in the comments below

**Comment by YunliQi** [comment]
abm_model/gif_plot.py contains classes for generating a gif figure.
The Point class is an object containing information for each patient on the gif figure(represented as a point in the figure)
The gif_plotter class is an object to implement the gif figure. To define such an object, you only need to input a Minicell object. To generate the gif figure, you only need to call the .plot() method. You can also specify the path and name to save the gif figure.
e.g. cell = Minicell()
       gif_plot = gif_plotter(cell)
       gif_plot.plot()

**Comment by tomcodewizard** [comment]
> abm_model/gif_plot.py contains classes for generating a gif figure. The Point class is an object containing information for each patient on the gif figure(represented as a point in the figure) The gif_plotter class is an object to implement the gif figure. To define such an object, you only need to input a Minicell object. To generate the gif figure, you only need to call the .plot() method. You can also specify the path and name to save the gif figure. e.g. cell = Minicell() gif_plot = gif_plotter(cell) gif_plot.plot()

Thanks! I am gonna add this to the wiki now
