### ISSUE TITLE
Variable names

### ISSUE THREAD

**Issue by mghosh00** [SABS-R3-Epidemiology/abm-project-2023#5]
Here are a list of variables we use in the project, along with their types and a short description:

- minicell.population_size: the total population for the model
- minicell.beta: the average number of people infected over the number of susceptible (it is beta).
- minicell.recovery_period: the average expiry date of the infection (it is 1/gamma).
- minicell.current_time the current time of the simulation, it is initialized 0 and then updated each time minicell.update() is called.
- minicell.s_list: the list of susceptible people
- minicell.i_list: the list of infected people
- minicell.r_list: the list of recovered people
- minicell.all_list: the list of all people
- minicell.events: the list of transictions triggered during the update, they will be handles at the end of the time-step changing statuses of people and moving them in the correct list
- person.name: a unique id for each person
- person.status: an object in the 'status' class. The 'status' class has three subclasses, with string representations 'Susceptible', 'Infected' and 'Recovered'
- Infected.expiry_date: the date to be recovered

**Comment by tomcodewizard** [comment]
We might want to rename the single-letter variables N, P, etc. in order to stick to python variable-naming conventions

**Comment by abbie-evans** [comment]
We should rename id as this is already a built-in python method
